# ---------------- #
#   Main Configs   #
# ---------------- #
url:  "https://yuanfeibi.github.io/Blog/"
baseurl:  "/Blog"
pagesurl: "/pages"
date_format: "ordinal"
title: jekyll-theme-solid
author: Zhuang Ma
modifier: Yuanfei Bi

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 20
paginate_path: /blog/page:num
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: yuanfeibi
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yuanfeibi
    repo: Blog
    oauth:
        client_id: 02fec91d3014cd25b77a
        client_secret: 25c65e0b17ec7dee76c4017f44d9253d1a3f3005
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
